Repository HistoricEngland/arches, pull requests merged in 2020-10, with the labels that each got.

#41 Bug 23594: Fixed heading cutting off
  arches/app/media/css/arches.css
  arches/app/templates/views/user-profile-manager.htm
Labels: bug

#44 crosshairs and header cut off fix into _he
  arches/app/media/css/arches.css
  arches/app/media/js/viewmodels/map-editor.js
  arches/app/media/js/viewmodels/map.js
  arches/app/media/js/views/components/search/map-filter.js
  arches/app/templates/views/user-profile-manager.htm
Labels: bug, enhancement

#47 Promote Stage to Prod - draw tool style
  arches/app/media/js/viewmodels/map-editor.js
  arches/app/media/js/views/components/cards/select-feature-layers.js
  arches/app/media/js/views/components/search/map-filter.js
Labels: enhancement
